### ISSUE TITLE
Can not build repo 1.20.x branch.

### ISSUE THREAD

**Issue by peaceshi** [MelanX/SkyblockBuilder#151]
### Minecraft version

1.20.1

### LibX version

*

### Skyblock Builder version

*

### Forge version

*

### The latest.log file

*

### Issue description

> Task :createMcpToSrg
Error getting artifact: net.minecraft:mappings_sugarcane:2023.07.02-1.20.1:null@zip from  MCPRepo
java.lang.NoSuchMethodError: 'de.siegmar.fastcsv.writer.CsvWriter de.siegmar.fastcsv.writer.CsvWriter.writeRow(java.lang.String[])'
        at org.parchmentmc.librarian.forgegradle.ParchmentChannelProvider.writeCsv(ParchmentChannelProvider.java:427)
        at org.parchmentmc.librarian.forgegradle.ParchmentChannelProvider.getMappingsFile(ParchmentChannelProvider.java:204)
        at org.moddingx.modgradle.plugins.mapping.provider.SugarcaneProvider.getMappingsFile(SugarcaneProvider.java:49)1

### Steps to reproduce

 .\gradlew.bat clean
 .\gradlew.bat build

**Comment by peaceshi** [comment]
https://github.com/ParchmentMC/Librarian/blob/c7f9878feb76d210aa65569fe38cad5297f439c5/src/main/java/org/parchmentmc/librarian/forgegradle/ParchmentChannelProvider.java#L422

**Comment by peaceshi** [comment]
https://github.com/osiegmar/FastCSV/issues/3

**Comment by MelanX** [comment]
It's working again :)
